---
- name: install the apache2 in ubuntu
  hosts: all
  become: yes
task:  
- name: update package and install the apache2
   apt:
   name: apache2
   update_cache: yes
   state: present
- name: install the php libapache2-mod-php php-mysql php-cli
   apt:
   name: php libapache2-mod-php php-mysql php-cli
   state: present
- name: copy the apache2 
    copy: /var/www/html/info.php
    src: apache2
 - name: Enable and start apache2
       systemd:
        name: apache2
        enabled: yes
        state: started   
     